# Tên của workflow, sẽ hiển thị trong tab "Actions" trên GitHub
name: Postman API Tests

# Điều kiện để kích hoạt workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Danh sách các công việc (jobs) sẽ được thực thi
jobs:
  run-api-tests:
    # Môi trường để chạy job, dùng Ubuntu mới nhất
    runs-on: ubuntu-latest

    # Các bước thực thi của job
    steps:
      # Bước 1: Checkout code từ repository về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Node.js (cần thiết cho Newman)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Bước 3: Cài đặt Newman
      - name: Install Newman
        run: npm install -g newman

      # Bước 4: Chạy collection REGISTER với data file
      - name: Run Register Collection
        continue-on-error: true
        run: |
          newman run "postman/API TESTING- REGISTER.postman_collection.json" \
            -e "postman/API testing_env.postman_environment.json" \
            -d "postman/RegisterData.csv" # <-- THÊM DATA FILE CHO REGISTER

      # Bước 5: Chạy collection LOGIN với data file và xuất ra môi trường đã được cập nhật
      - name: Run Login Collection
        continue-on-error: true
        run: |
          newman run "postman/API TESTING- LOGIN.postman_collection.json" \
            -e "postman/API testing_env.postman_environment.json" \
            -d "postman/LoginData.csv" \ # <-- THÊM DATA FILE CHO LOGIN
            --export-environment "postman/updated-env.json"

      # Bước 6: Chạy collection SEARCH với data file và môi trường đã được cập nhật
      - name: Run Search Collection
        continue-on-error: true
        run: |
          newman run "postman/API TESTING- SEARCH.postman_collection.json" \
            -e "postman/updated-env.json" \
            -d "postman/SearchData.csv" # <-- THÊM DATA FILE CHO SEARCH
